kafka:
  bootstrap_servers:
    - "localhost:29092"

  topics:
    raw_reviews: "raw_reviews"

  producers:
    yelp_review_producer:
      topic: 'raw_reviews'
      client_id: 'python.yelp_review_producer'
      bootstrap_servers:
        - "localhost:29092"
      time_range_ms:
        min: 3000
        max: 15000


  consumers:
    yelp_review_consumer:
      topic: 'raw_reviews'
      client_id: 'spark.yelp_review_consumer'
      bootstrap_servers:
        - "kafka:9092"    
      group_id: 'spark-stream-group'

    yelp_raw_review_consumer:
      topic: 'raw_reviews'
      client_id: 'python.yelp_raw_review_consumer'
      bootstrap_servers:
        - "kafka:9092"    
      group_id: 'python-stream-group'