checkpoints_db:
  host: localhost
  port: 27017
  database: streaming_nlp
  collection: checkpoints
  username: admin
  password: password

# host mongodb as it is running inside docker network `local`
enriched_review:
  host: mongodb
  port: 27017
  database: streaming_nlp
  collection: enriched_reviews
  username: admin
  password: password

raw_review_collection:
  host: localhost
  port: 27017
  database: streaming_nlp
  collection: raw_reviews
  username: admin
  password: password